name: Mirror main to public

on:
  push:
    branches: [ main ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirror
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }} # PAT with repo access to mirror repo
        run: |
          git config user.name "mirror-bot"
          git config user.email "mirror-bot@users.noreply.github.com"
          git remote add mirror https://x-access-token:${MIRROR_TOKEN}@github.com/${{ github.repository_owner }}/Stories-and-Novels-public-mirror.git
          git push --force mirror main:main
