name: Mirror main to public

on:
  push:
    branches: [ main ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo (no stored creds)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false   # <-- critical

      - name: Configure git
        run: |
          git config --global user.name "mirror-bot"
          git config --global user.email "mirror-bot@users.noreply.github.com"

      - name: Add mirror remote (PAT)
        env:
          MIRROR_TOKEN: ${{ secrets.MIRRORKEY }}
        run: |
          git remote add mirror https://x-access-token:${MIRROR_TOKEN}@github.com/RishiBaner/Stories-and-Novels-public-mirror.git
          git remote -v

      - name: Push to public mirror
        run: |
          git push --force --tags mirror main:main
