name: Mirror main to public

on:
  push:
    branches: [ main ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to public mirror
        env:
          MIRROR_TOKEN: ${{ secrets.MIRRORKEY }} # Uses your existing secret
        run: |
          git config --global user.name "mirror-bot"
          git config --global user.email "mirror-bot@users.noreply.github.com"
          git remote add mirror https://x-access-token:${MIRROR_TOKEN}@github.com/${{ github.repository_owner }}/Stories-and-Novels-public-mirror.git
          git push --force --tags mirror main:main

